### PR TITLE
Notification tones fixed

### PR DESCRIPTION
**Pull request by sammargh**
Notifications work properly now based off the user settings within the iPhone. Of course this will break if a hacker decides to use their own custom setting, they get Tritone.

### CODE REVIEW

**Comment by timnovinger** [comment]
So this doesn't take into account the new tones that Apple just introduced for SMS not too long ago?

**Comment by Drudoo** [comment]
Sweet. Just tested and it works perfectly. 
@timnovinger doesn't look like it, but it could probably be fixed quickly, if you get the right AudioServicesPlayAlertSound code for each of them.

**Comment by sammargh** [comment]
Derp. I can add those in. Hold on.

**Comment by sammargh** [comment]
http://www.iphonedevwiki.net/index.php/AudioServices

that's the list of audio tones and the respective codes.. just use those so I don't have to initiate another pull request

**Comment by sammargh** [comment]
There's the full set of notification tones

**Comment by timnovinger** [comment]
Awesome job dude, you rock!

It's a little interesting that Apple neglected IDs 1011 and 1012 and went straight to 1013, lol.

**Pull request merged**
